repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "(docs/.*|integration/tpl/files/.*)"
      - id: check-yaml
        exclude: "examples/.*"
      - id: check-added-large-files
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.16
    hooks:
      - id: go-mod-tidy
  - repo: local
    hooks:
      - id: lint
        name: lint
        language: system
        entry: make
        args: ["lint"]
        types: ["go"]
        pass_filenames: false
  - repo: local
    hooks:
      - id: check-component-versions
        name: check-component-versions
        language: system
        entry: make
        args: ["check-component-versions"]
        pass_filenames: false
        always_run: true
