apiVersion: v1
kind: Service
metadata:
  name: pomerium-proxy-service
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: https
  selector:
    app: pomerium-proxy
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomerium-proxy
  labels:
    app: pomerium-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pomerium-proxy
  template:
    metadata:
      labels:
        app: pomerium-proxy
    spec:
      containers:
        - image: pomerium/pomerium:latest
          name: pomerium-proxy
          args:
            - --config=/etc/pomerium/config.yaml
          ports:
            - containerPort: 443
              name: https
              protocol: TCP
          env:
            - name: SERVICES
              value: proxy
            - name: SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: shared-secret
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: cookie-secret
                  key: cookie-secret
            - name: CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: certificate
                  key: certificate
            - name: CERTIFICATE_KEY
              valueFrom:
                secretKeyRef:
                  name: certificate-key
                  key: certificate-key
          readinessProbe:
            httpGet:
              path: /ping
              port: 443
              scheme: HTTPS
          livenessProbe:
            httpGet:
              path: /ping
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /etc/pomerium/
              name: config
      volumes:
        - name: config
          configMap:
            name: config
