name: Release

on:
  release:
    types:
      - published

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x

      - name: Set up Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: pomerium-io
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Gcloud login
        run: gcloud auth configure-docker

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --config .github/goreleaser.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPARITOR_GITHUB_TOKEN: ${{ secrets.APPARITOR_GITHUB_TOKEN }}

      - name: Get tag name
        id: tagName
        run: |
          TAG=$(git describe --tags --exact-match)
          echo ::set-output name=tag::${TAG}
          echo ::set-output name=version::${TAG#v}

      - name: Install jfrog cli
        uses: jfrog/setup-jfrog-cli@v1

      - name: Configure jfrog cli
        run: |
          jfrog bt config --user ${{ secrets.BINTRAY_USER }} --key ${{ secrets.BINTRAY_KEY }}

      - name: Upload packages to bintray beta channel
        if: "contains(steps.tagName.outputs.version, 'rc') == 1"
        run: |
          VERSION=${{ steps.tagName.outputs.version }}
          jfrog bt upload --publish dist/pomerium-${VERSION}-1.x86_64.rpm pomerium/enterprise-yum/pomerium/${VERSION} centos/8/x86_64/beta/
          jfrog bt upload --publish dist/pomerium-cli-${VERSION}-1.x86_64.rpm pomerium/enterprise-yum/pomerium/${VERSION} centos/8/x86_64/beta/

      - name: Upload packages to bintray stable channel
        if: "contains(steps.tagName.outputs.version, 'rc') == 0"
        run: |
          VERSION=${{ steps.tagName.outputs.version }}
          jfrog bt upload --publish dist/pomerium-${VERSION}-1.x86_64.rpm pomerium/enterprise-yum/pomerium/${VERSION} centos/8/x86_64/stable/
          jfrog bt upload --publish dist/pomerium-cli-${VERSION}-1.x86_64.rpm pomerium/enterprise-yum/pomerium/${VERSION} centos/8/x86_64/stable/

      - name: Find latest tag
        id: latestTag
        run: |
          LATEST_TAG=$(git tag | grep -vi 'rc' | sort --version-sort | tail -1)
          echo "::set-env name=LATEST_TAG::$LATEST_TAG"

      - name: Publish latest tag
        if: "env.LATEST_TAG == steps.tagName.outputs.tag"
        run: |
          docker tag pomerium/pomerium:${{ env.LATEST_TAG }} pomerium/pomerium:latest
          docker push pomerium/pomerium:latest

          docker tag pomerium/pomerium:arm64v8-${{ env.LATEST_TAG }} pomerium/pomerium:arm64v8-latest
          docker push pomerium/pomerium:arm64v8-latest

          docker tag gcr.io/pomerium-io/pomerium:${{ env.LATEST_TAG }}-cloudrun gcr.io/pomerium-io/pomerium:latest-cloudrun
          docker push gcr.io/pomerium-io/pomerium:latest-cloudrun
